### ISSUE TITLE
why i can not login using admin/xaps?

### ISSUE THREAD

**Issue by xiewandongqq** [freeacs/tr069#2]
The web show : Error while authenticating: Access denied for user 'xaps'@'localhost' (using password: YES)

**Comment by freeacs** [comment]
the problem is most likely that the web cannot log into mysql server. check password settings in xaps-web.properties and try to log on directly into mysql using command line 'mysql' to test the settings. also see forum for freeacs for this kind of questions. 

kind regards
morten s

**Comment by linpf** [comment]
Most likely a bug in the installation script 

sed -i 's/xaps\/$oldacsdbpw/xaps\/$acsdbpw/g' *.properties

should be 

sed -i 's/xaps\/'$oldacsdbpw'/xaps\/'$acsdbpw'/g' *.properties

**Comment by freeacs** [comment]
I have updated the installation script according to this suggestion. I gather this may help to handle "odd" passwords? Thanks for your input!
