### ISSUE TITLE
SetParameterAttributes xml message has a syntax error

### ISSUE THREAD

**Issue by pittcrew89** [freeacs/tr069#3]
In the file SPAreq.java the end tag for SetParameterAttributesStruct is missing an s, so it is currently SetParameterAttributeStruct, this causes the CPE xml parser to throw a syntax error.

**Comment by freeacs** [comment]
You're right about that. How did you encounter this bug (what was the scenario?) I think this bug can only be triggered through usage of the test-system?  Anyway, I will fix it and release a new version some time soon.

**Comment by mortensimon** [comment]
Released a new version with the fix.

**Comment by pittcrew89** [comment]
Hi Morten,

Great! We appreciate the quick turnaround. I'm out of the office on family business, but I'll be able to check this in the next few days. We're using FreeACS to help us test our cpe tr069 implementation and I was using FreeACS in the test mode when I found the issue.  I program in 'C' but I had downloaded the Java code and I was going to try and build it from source but hadn't got all the projects set up correctly in eclipse yet. 

Thanks again for your quick support. 

Jim Pitt

**Comment by mortensimon** [comment]
Yes, I was hoping this was about testing, I would have been surprised if
this error was in the regular provisioning code path. Hopefully things will
work now. Thanks for your find!

kind regards
Morten S

2016-02-10 21:04 GMT+01:00 pittcrew89 notifications@github.com:
